### ISSUE TITLE
Wrong command in help file

### ISSUE THREAD

**Issue by TheNomad11** [PhiTux/dailytxt-decrypt-cli#1]
The cli help suggests following command:

`dailytxt_decrypt [-a | --all] [--to-single-file] (-u | --user) <username> (-p | --password) <password> <from_path> <to_path>

it should be dailytxt_decrypt-cli

So how I made it work:

`./dailytxt-decrypt-cli --all --to-single-file --user myusername --password mypassword . ./backup/`

or 

`./dailytxt-decrypt-cli --all --user myusername --password mypassword . ./backup/`

**Comment by PhiTux** [comment]
Thank you very much, it's fixed with the new release 1.0.1 !
